// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6bCSctxl-u5Vxr7ulBAMon0HBoZZOgEQ',
    appId: '1:810881038751:web:427dd46020d6947353a5aa',
    messagingSenderId: '810881038751',
    projectId: 'stressmanagement-d47df',
    authDomain: 'stressmanagement-d47df.firebaseapp.com',
    storageBucket: 'stressmanagement-d47df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdX54d_butgS4Z19kTGSJVU_mDzlmMvWM',
    appId: '1:810881038751:android:e8f018bcec82680453a5aa',
    messagingSenderId: '810881038751',
    projectId: 'stressmanagement-d47df',
    storageBucket: 'stressmanagement-d47df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdNZmJtDANDPQriwaVjzaqjS6JoV56ab0',
    appId: '1:810881038751:ios:f05fa6fada5b1f9553a5aa',
    messagingSenderId: '810881038751',
    projectId: 'stressmanagement-d47df',
    storageBucket: 'stressmanagement-d47df.appspot.com',
    iosBundleId: 'com.example.stressManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdNZmJtDANDPQriwaVjzaqjS6JoV56ab0',
    appId: '1:810881038751:ios:d08931b6f1e08ca953a5aa',
    messagingSenderId: '810881038751',
    projectId: 'stressmanagement-d47df',
    storageBucket: 'stressmanagement-d47df.appspot.com',
    iosBundleId: 'com.example.stressManagementApp.RunnerTests',
  );
}
